# Generated by Django 5.0.2 on 2024-03-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voyage_number', models.CharField(max_length=50)),
                ('arrival_date', models.DateField()),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.vessel')),
            ],
        ),
    ]
