# Generated by Django 5.0.2 on 2024-03-05 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billoflading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=200)),
                ('bol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.billoflading')),
            ],
        ),
    ]
